name: portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_bloc: ^9.0.0
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  animated_text_kit: ^4.2.3
  emailjs: ^4.0.0
  visibility_detector: ^0.4.0+2
  fluttertoast: ^8.2.12



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/lotties/



  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/font/Helvetica.ttf
    - family: Airbeat
      fonts:
        - asset: assets/font/airbeat-eaw0j.ttf
